In [1]:
#importing Trade and Quotes data
import pandas as pd
TRADES_FILE = 'EQY_DJIA_TRADE_20190814.p'
QUOTES_FILE = 'EQY_DJIA_QUOTES_20190814.p'
dtrades = pd.read_pickle(TRADES_FILE)
dquotes = pd.read_pickle(QUOTES_FILE)

In [2]:
#making the data visable between a time frame
tradeTime = dtrades.between_time('9:30', '16:00')
quoteTime = dquotes.between_time('9:30', '16:00')

In [3]:
tradeTime.head()

                              Exchange Symbol  Trade Volume  Trade Price
2019-08-14 09:30:00.000502536        Q   AAPL            20       203.28
2019-08-14 09:30:00.001298427        P   AAPL            20       203.24
2019-08-14 09:30:00.026632450        Q   AAPL           100       203.25
2019-08-14 09:30:00.028495896        K   AAPL           300       203.16
2019-08-14 09:30:00.028501697        K   AAPL           200       203.16

In [4]:
#only seeing the trades and quotes from AAPL
groupTrade=tradeTime.groupby(['Symbol']).size().head(30)

In [5]:
sQ = tradeTime[tradeTime.Symbol == 'AAPL']

In [6]:
sT = quoteTime[quoteTime.Symbol == 'AAPL']

In [7]:
# merging the trades and quotes data set
aapl = pd.merge_asof(sT, sQ, left_index = True, right_index = True)

In [8]:

aapl.head()

,Exchange_x,Symbol_x,Bid_Price,Bid_Size,Offer_Price,Offer_Size,Best_Bid_Exchange,Best_Bid_Price,Best_Bid_Size,Best_Offer_Exchange,Best_Offer_Price,Best_Offer_Size,Exchange_y,Symbol_y,Trade Volume,Trade Price
2019-08-14 09:30:00.026527434,Q,AAPL,203.24,1,203.29,38,Q,203.24,1,P,203.25,1,P,AAPL,20,203.24
2019-08-14 09:30:00.026630266,Q,AAPL,203.01,1,203.29,38,K,203.15,5,P,203.25,1,P,AAPL,20,203.24
2019-08-14 09:30:00.053839544,K,AAPL,203.15,1,203.40,1,K,203.15,1,P,203.25,1,K,AAPL,325,203.15
2019-08-14 09:30:00.053851411,K,AAPL,203.01,2,203.40,1,K,203.01,2,P,203.25,1,K,AAPL,100,203.15
2019-08-14 09:30:00.098047380,K,AAPL,203.00,3,203.15,1,Q,203.01,1,K,203.15,1,Q,AAPL,119,203.09

In [10]:
# calculating financal calculations to better understand stocks
aapl['midpoint']= (aapl['Best_Bid_Price'] + aapl['Best_Offer_Price'])/2

aapl.head()

,Exchange_x,Symbol_x,Bid_Price,Bid_Size,Offer_Price,Offer_Size,Best_Bid_Exchange,Best_Bid_Price,Best_Bid_Size,Best_Offer_Exchange,Best_Offer_Price,Best_Offer_Size,Exchange_y,Symbol_y,Trade Volume,Trade Price,midpoint
2019-08-14 09:30:00.026527434,Q,AAPL,203.24,1,203.29,38,Q,203.24,1,P,203.25,1,P,AAPL,20,203.24,203.245
2019-08-14 09:30:00.026630266,Q,AAPL,203.01,1,203.29,38,K,203.15,5,P,203.25,1,P,AAPL,20,203.24,203.200
2019-08-14 09:30:00.053839544,K,AAPL,203.15,1,203.40,1,K,203.15,1,P,203.25,1,K,AAPL,325,203.15,203.200
2019-08-14 09:30:00.053851411,K,AAPL,203.01,2,203.40,1,K,203.01,2,P,203.25,1,K,AAPL,100,203.15,203.130
2019-08-14 09:30:00.098047380,K,AAPL,203.00,3,203.15,1,Q,203.01,1,K,203.15,1,Q,AAPL,119,203.09,203.080

In [11]:
aapl['Percent Quoted Spread']=  ((aapl['Best_Offer_Price'] - aapl['Best_Bid_Price']) / aapl['midpoint'])

In [12]:
aapl.head()

,Exchange_x,Symbol_x,Bid_Price,Bid_Size,Offer_Price,Offer_Size,Best_Bid_Exchange,Best_Bid_Price,Best_Bid_Size,Best_Offer_Exchange,Best_Offer_Price,Best_Offer_Size,Exchange_y,Symbol_y,Trade Volume,Trade Price,midpoint,Percent Quoted Spread
2019-08-14 09:30:00.026527434,Q,AAPL,203.24,1,203.29,38,Q,203.24,1,P,203.25,1,P,AAPL,20,203.24,203.245,0.000049
2019-08-14 09:30:00.026630266,Q,AAPL,203.01,1,203.29,38,K,203.15,5,P,203.25,1,P,AAPL,20,203.24,203.200,0.000492
2019-08-14 09:30:00.053839544,K,AAPL,203.15,1,203.40,1,K,203.15,1,P,203.25,1,K,AAPL,325,203.15,203.200,0.000492
2019-08-14 09:30:00.053851411,K,AAPL,203.01,2,203.40,1,K,203.01,2,P,203.25,1,K,AAPL,100,203.15,203.130,0.001182
2019-08-14 09:30:00.098047380,K,AAPL,203.00,3,203.15,1,Q,203.01,1,K,203.15,1,Q,AAPL,119,203.09,203.080,0.000689

In [13]:
aapl['Percent Effective Spread']=  (2 * abs(aapl['Trade Price'] - aapl['midpoint'])) / aapl['midpoint']

In [14]:
aapl.head()

,Exchange_x,Symbol_x,Bid_Price,Bid_Size,Offer_Price,Offer_Size,Best_Bid_Exchange,Best_Bid_Price,Best_Bid_Size,Best_Offer_Exchange,Best_Offer_Price,Best_Offer_Size,Exchange_y,Symbol_y,Trade Volume,Trade Price,midpoint,Percent Quoted Spread,Percent Effective Spread
2019-08-14 09:30:00.026527434,Q,AAPL,203.24,1,203.29,38,Q,203.24,1,P,203.25,1,P,AAPL,20,203.24,203.245,0.000049,0.000049
2019-08-14 09:30:00.026630266,Q,AAPL,203.01,1,203.29,38,K,203.15,5,P,203.25,1,P,AAPL,20,203.24,203.200,0.000492,0.000394
2019-08-14 09:30:00.053839544,K,AAPL,203.15,1,203.40,1,K,203.15,1,P,203.25,1,K,AAPL,325,203.15,203.200,0.000492,0.000492
2019-08-14 09:30:00.053851411,K,AAPL,203.01,2,203.40,1,K,203.01,2,P,203.25,1,K,AAPL,100,203.15,203.130,0.001182,0.000197
2019-08-14 09:30:00.098047380,K,AAPL,203.00,3,203.15,1,Q,203.01,1,K,203.15,1,Q,AAPL,119,203.09,203.080,0.000689,0.000098

In [15]:
aapl['Depth'] = aapl['Best_Bid_Size'] + aapl['Best_Offer_Size']

In [16]:
aapl.head()

,Exchange_x,Symbol_x,Bid_Price,Bid_Size,Offer_Price,Offer_Size,Best_Bid_Exchange,Best_Bid_Price,Best_Bid_Size,Best_Offer_Exchange,Best_Offer_Price,Best_Offer_Size,Exchange_y,Symbol_y,Trade Volume,Trade Price,midpoint,Percent Quoted Spread,Percent Effective Spread,Depth
2019-08-14 09:30:00.026527434,Q,AAPL,203.24,1,203.29,38,Q,203.24,1,P,203.25,1,P,AAPL,20,203.24,203.245,0.000049,0.000049,2
2019-08-14 09:30:00.026630266,Q,AAPL,203.01,1,203.29,38,K,203.15,5,P,203.25,1,P,AAPL,20,203.24,203.200,0.000492,0.000394,6
2019-08-14 09:30:00.053839544,K,AAPL,203.15,1,203.40,1,K,203.15,1,P,203.25,1,K,AAPL,325,203.15,203.200,0.000492,0.000492,2
2019-08-14 09:30:00.053851411,K,AAPL,203.01,2,203.40,1,K,203.01,2,P,203.25,1,K,AAPL,100,203.15,203.130,0.001182,0.000197,3
2019-08-14 09:30:00.098047380,K,AAPL,203.00,3,203.15,1,Q,203.01,1,K,203.15,1,Q,AAPL,119,203.09,203.080,0.000689,0.000098,2

In [17]:
def pit(pes,pqs):
    if pes < pqs:
        return 1
    else:
        return 0

In [18]:
aapl['Price Improvement'] = aapl.apply(lambda x: pit(x['Percent Effective Spread'],x['Percent Quoted Spread']), axis = 1)

In [19]:
aapl.head()

,Exchange_x,Symbol_x,Bid_Price,Bid_Size,Offer_Price,Offer_Size,Best_Bid_Exchange,Best_Bid_Price,Best_Bid_Size,Best_Offer_Exchange,...,Best_Offer_Size,Exchange_y,Symbol_y,Trade Volume,Trade Price,midpoint,Percent Quoted Spread,Percent Effective Spread,Depth,Price Improvement
2019-08-14 09:30:00.026527434,Q,AAPL,203.24,1,203.29,38,Q,203.24,1,P,...,1,P,AAPL,20,203.24,203.245,0.000049,0.000049,2,0
2019-08-14 09:30:00.026630266,Q,AAPL,203.01,1,203.29,38,K,203.15,5,P,...,1,P,AAPL,20,203.24,203.200,0.000492,0.000394,6,1
2019-08-14 09:30:00.053839544,K,AAPL,203.15,1,203.40,1,K,203.15,1,P,...,1,K,AAPL,325,203.15,203.200,0.000492,0.000492,2,1
2019-08-14 09:30:00.053851411,K,AAPL,203.01,2,203.40,1,K,203.01,2,P,...,1,K,AAPL,100,203.15,203.130,0.001182,0.000197,3,1
2019-08-14 09:30:00.098047380,K,AAPL,203.00,3,203.15,1,Q,203.01,1,K,...,1,Q,AAPL,119,203.09,203.080,0.000689,0.000098,2,1

In [20]:
def TT(pes,pqs):
    if pes > pqs:
        return 1
    else:
        return 0

In [21]:
aapl['Trade Through'] = aapl.apply(lambda x: TT(x['Percent Effective Spread'],x['Percent Quoted Spread']), axis = 1)

In [22]:
aapl.head()

,Exchange_x,Symbol_x,Bid_Price,Bid_Size,Offer_Price,Offer_Size,Best_Bid_Exchange,Best_Bid_Price,Best_Bid_Size,Best_Offer_Exchange,...,Exchange_y,Symbol_y,Trade Volume,Trade Price,midpoint,Percent Quoted Spread,Percent Effective Spread,Depth,Price Improvement,Trade Through
2019-08-14 09:30:00.026527434,Q,AAPL,203.24,1,203.29,38,Q,203.24,1,P,...,P,AAPL,20,203.24,203.245,0.000049,0.000049,2,0,0
2019-08-14 09:30:00.026630266,Q,AAPL,203.01,1,203.29,38,K,203.15,5,P,...,P,AAPL,20,203.24,203.200,0.000492,0.000394,6,1,0
2019-08-14 09:30:00.053839544,K,AAPL,203.15,1,203.40,1,K,203.15,1,P,...,K,AAPL,325,203.15,203.200,0.000492,0.000492,2,1,0
2019-08-14 09:30:00.053851411,K,AAPL,203.01,2,203.40,1,K,203.01,2,P,...,K,AAPL,100,203.15,203.130,0.001182,0.000197,3,1,0
2019-08-14 09:30:00.098047380,K,AAPL,203.00,3,203.15,1,Q,203.01,1,K,...,Q,AAPL,119,203.09,203.080,0.000689,0.000098,2,1,0

In [35]:
#creating a function that that builds a summarizing dataframe which can used multiple times to answer questions before investing  


groupedQuotes = quoteTime.groupby('Symbol')
groupedTrades = tradeTime.groupby('Symbol')
def sumBuild(tick):
    groupedTrades = tradeTime.groupby('Symbol')
    dt = groupedTrades.get_group(tick)
    dq = groupedQuotes.get_group(tick)
    tradeQuote = pd.merge_asof(dt, dq, left_index = True, right_index = True)
    tradeQuote.dropna()
    tradeQuote['midpoint']= (tradeQuote['Best_Bid_Price'] + tradeQuote['Best_Offer_Price'])/2
    tradeQuote['Percent Quoted Spread']=  ((tradeQuote['Best_Offer_Price'] - tradeQuote['Best_Bid_Price']) / tradeQuote['midpoint']) 
    tradeQuote['Percent Effective Spread']=  (2 * abs(tradeQuote['Trade Price'] - tradeQuote['midpoint'])) / tradeQuote['midpoint']
    tradeQuote['Depth'] = tradeQuote['Best_Bid_Size'] + tradeQuote['Best_Offer_Size']
    tradeQuote['Price Improvement'] = tradeQuote.apply(lambda x: pit(x['Percent Effective Spread'],x['Percent Quoted Spread']), axis = 1)
    tradeQuote['Trade Through'] = tradeQuote.apply(lambda x: TT(x['Percent Effective Spread'],x['Percent Quoted Spread']), axis = 1)
    pqs = tradeQuote['Percent Quoted Spread'].mean()
    pes = tradeQuote['Percent Effective Spread'].mean()
    depth = tradeQuote['Depth'].mean()
    pi = tradeQuote['Price Improvement'].mean()
    tt = tradeQuote['Trade Through'].mean()
    return pqs, pes, depth, pi, tt

In [36]:
pqs, pes, depth, pi, tt = sumBuild('AAPL')

In [37]:
pqs

0.0001291115247518151

In [32]:
#developing the dataframe
summary = pd.DataFrame()
groupedQuotes = quoteTime.groupby('Symbol')
groupedTrades = tradeTime.groupby('Symbol')
ticks=groupedQuotes.groups.keys()
for tick in ticks: 
    pqs, pes, depth, pi, tt = sumBuild(tick)
    summary.at[tick, 'Percent Quoted Spread'] = pqs
    summary.at[tick, 'Percent Effective Spread'] = pes
    summary.at[tick, 'Depth'] = depth
    summary.at[tick, 'Trade Throughs'] = tt
    summary.at[tick, 'Price Improvement'] = pi

In [34]:
summary

,Percent Quoted Spread,Percent Effective Spread,Depth,Trade Throughs,Price Improvement
AAPL,0.000129,0.000105,5.694311,0.202850,0.568588
AXP,0.000208,0.000155,4.615911,0.191951,0.520207
BA,0.000365,0.000235,4.254989,0.108978,0.735476
CAT,0.000273,0.000195,4.671142,0.157184,0.556210
CSCO,0.000192,0.000176,24.240625,0.278430,0.453464
CVX,0.000185,0.000147,4.831980,0.197337,0.537083
DIS,0.000174,0.000125,5.317136,0.153394,0.628028
DOW,0.000460,0.000329,7.703182,0.207449,0.540661
GS,0.000402,0.000269,3.163196,0.113020,0.697784
HD,0.000286,0.000207,3.549384,0.140870,0.647257
IBM,0.000315,0.000211,3.978001,0.154980,0.653703
INTC,0.000194,0.000180,40.568029,0.283699,0.389783
JNJ,0.000139,0.000108,5.540962,0.152464,0.485222
JPM,0.000118,0.000101,9.456402,0.240395,0.461310
KO,0.000169,0.000143,25.226783,0.256788,0.447682
MCD,0.000253,0.000160,3.220191,0.133425,0.682503
MMM,0.000421,0.000296,3.371333,0.126049,0.675750
MRK,0.000124,0.000110,10.935396,0.246697,0.407819
MSFT,0.000102,0.000092,9.647594,0.179408,0.407008
NKE,0.000193,0.000143,7.286142,0.224201,0.485105
PFE,0.000266,0.000230,77.486709,0.264884,0.444601
PG,0.000129,0.000097,5.478905,0.227435,0.502837
TRV,0.000437,0.000256,3.155580,0.114088,0.731998
UNH,0.000402,0.000262,3.281489,0.113101,0.708000
UTX,0.000337,0.000222,4.050730,0.135096,0.625117
V,0.000223,0.000154,3.839587,0.170474,0.634598
VZ,0.000167,0.000136,20.729869,0.254069,0.459637
WBA,0.000272,0.000211,9.907859,0.247561,0.506095
WMT,0.000204,0.000153,5.832215,0.210271,0.526930
XOM,0.000142,0.000136,17.921521,0.238391,0.413139